name: nostr_mail_client
description: "Everyone has an email address but nobody own it. Nostr solve this."
publish_to: 'none'
version: 0.1.2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  get: ^4.7.3
  ndk: ^0.7.1-dev.1
  path_provider: ^2.1.5
  sembast: ^3.8.6
  toastification: ^3.0.3
  nostr_mail: ^1.2.2
  ndk_rust_verifier: ^0.5.0
  sembast_cache_manager: ^1.0.6
  http: ^1.6.0
  intl: ^0.20.2
  sembast_web: ^2.4.3
  nostr_widgets: ^1.2.2
  path: ^1.9.1
  url_launcher: ^6.3.2
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
